### Numpy

NumPy is a fundamental library for scientific computing in Python. It provides support for arrays and matrices, along with a collection of mathematical function to operate on these data structures. In this lesson, we will cover the basics of NumPy, focusing on arrays and vectoried operations.


In [1]:
# !pip install numpy

In [ ]:
import numpy as np

## create arrat using numpy
## create a 1D array

arr1 = np.array([1,2,3,4,5])
print(arr1)
print(type(arr1))
print(arr1.shape)

[[1 2 3 4 5]
 [5 4 3 2 1]]
<class 'numpy.ndarray'>
(2, 5)


In [12]:
arr2 = np.array([1,2,3,4,5])
arr2.reshape(1,5)
arr2.reshape(2,5)

ValueError: cannot reshape array of size 5 into shape (2,5)

In [11]:
arr3 = np.array([[1,2,3], [3,2,1]])

print(arr3.shape)

(2, 3)


In [14]:
np.arange(0, 10, 2).reshape(5,1)

array([[0],
       [2],
       [4],
       [6],
       [8]])

In [16]:
np.ones((3,4))

array([[1., 1., 1., 1.],
       [1., 1., 1., 1.],
       [1., 1., 1., 1.]])

In [17]:
## identity matrix

np.eye(3)

array([[1., 0., 0.],
       [0., 1., 0.],
       [0., 0., 1.]])

In [20]:
## Attributes of numpy

arr = np.array([[1,2,3], [4,5,6]])

print("Array: \n", arr)
print("Shape: ", arr.shape)
print("Number of dimensions: ", arr.ndim)
print("Size (number of elements): ", arr.size)
print("Data type: ", arr.dtype)
print("Item size (in bytes): ", arr.itemsize)

Array: 
 [[1 2 3]
 [4 5 6]]
Shape:  (2, 3)
Number of dimensions:  2
Size (number of elements):  6
Data type:  int64
Item size (in bytes):  8


In [21]:
### Numpy Vectorized Operation

arr1 = np.array([1,2,3,4,5])
arr2 = np.array([10,20,30,40,50])

## Element wise Addition
print("Addition: ", arr1+arr2)

## Element wise Subtraction
print("Subtraction: ", arr1 - arr2)

## Element wise multiplication
print("Multiplication: ", arr1 * arr2)

## Element wise division
print("Multiplication: ", arr1 / arr2)

Addition:  [11 22 33 44 55]
Subtraction:  [ -9 -18 -27 -36 -45]
Multiplication:  [ 10  40  90 160 250]
Multiplication:  [0.1 0.1 0.1 0.1 0.1]


In [22]:
## Universal function
arr = np.array([2,3,4,5,6])

## Square root
print(np.sqrt(arr))

## Exponential
print(np.exp(arr))

## Sine
print(np.sin(arr))

## natural log
print(np.log(arr))

[1.41421356 1.73205081 2.         2.23606798 2.44948974]
[  7.3890561   20.08553692  54.59815003 148.4131591  403.42879349]
[ 0.90929743  0.14112001 -0.7568025  -0.95892427 -0.2794155 ]
[0.69314718 1.09861229 1.38629436 1.60943791 1.79175947]


In [23]:
## array slicing and indexing

arr = np.array([[1,2,3,4,], [5,6,7,8,], [9,10,11,12]])
print("Array: \n", arr)

Array: 
 [[ 1  2  3  4]
 [ 5  6  7  8]
 [ 9 10 11 12]]


In [36]:
## Important for slicing

print(arr[1:,2:]) 
print(arr[0:2, 2:])

[[ 7  8]
 [11 12]]
[[3 4]
 [7 8]]


In [37]:
arr[0,0] = 100
print(arr)

[[100   2   3   4]
 [  5   6   7   8]
 [  9  10  11  12]]


In [38]:
arr[1:] = 100
print(arr)

[[100   2   3   4]
 [100 100 100 100]
 [100 100 100 100]]


In [ ]:
## Statistical concepts -- Normalisation
## to have a mean of 0 and standard deviation of 1

data = np.array([1,2,3,4,5])

# calculate the mean and standard deviation
mean = np.mean(data)
std_dev = np.std(data)

# normalize the data
normalized_data = (data - mean) / std_dev
print("Normalized data: ", normalized_data)

# Output:
# Normalized data:  [-1.41421356 -0.70710678  0.          0.70710678  1.41421356]

Normalized data:  [-1.41421356 -0.70710678  0.          0.70710678  1.41421356]


In [40]:
# mean, median, std, var (variance) are the methods applicable on numpy array

In [46]:
## Logical Operations

data = np.array([1,2,3,4,5,6,7,8,9,10])

data[(data > 5) & (data < 9)]

array([6, 7, 8])